version: 3.7
services:
  rabbit1:
    image: rabbitmq:3.8.1-management
    volumes:
      - $PWD/rabbitmq-data:/var/lib/rabbitmq/mnesia/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbit2:
    image: rabbitmq:3.8.1-management
    volumes:
      - $PWD/rabbitmq-data:/var/lib/rabbitmq/mnesia/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5673:5672"
      - "15673:15672"
  rabbit3:
    image: rabbitmq:3.8.1-management
    volumes:
      - $PWD/rabbitmq-data:/var/lib/rabbitmq/mnesia/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5674:5672"
      - "15674:15672"
