version: '3.7'
services:
  rabbit1:
    image: rabbitmq:3.8.1-management
    hostname: rabbit1
    container_name: rabbit1
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/
      - type: bind
        source: $PWD/prepare_cluster.sh
        target: /prepare_cluster.sh
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE=asdflw23r2kemcald
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbit2:
    image: rabbitmq:3.8.1-management
    hostname: rabbit2
    container_name: rabbit2
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/
      - type: bind
        source: $PWD/prepare_cluster.sh
        target: /prepare_cluster.sh
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE=asdflw23r2kemcald
    ports:
      - "5673:5672"
      - "15673:15672"
    depends_on:
      - rabbit1
  rabbit3:
    image: rabbitmq:3.8.1-management
    hostname: rabbit3
    container_name: rabbit3
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/
      - type: bind
        source: $PWD/prepare_cluster.sh
        target: /prepare_cluster.sh
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE=asdflw23r2kemcald
    ports:
      - "5674:5672"
      - "15674:15672"
    depends_on:
      - rabbit1
  management:
    image: debian:buster-slim
    hostname: side-container
    container_name: side-container
    tty: true

volumes:
  rabbitmq-data:
